01.値と型と変数
shumpei07/hennsuu1 pull request #1
Opened 2023-09-01 07:01 UTC by shumpei07

# php基礎　4.変数
変数の宣言・代入・参照の学習。
			
# やったこと
phpの「01.値と型と変数」に関する課題の提出。
ご確認よろしくお願いします。

2023-09-01 07:55 UTC, tatsuki-uchiyama requested changes

2023-09-01 07:55 UTC, tatsuki-uchiyama commented on lesson3.php
> +echo $human['age']['gender'];
フォーマット通り　歳・の字を表示するようにして下さい。

2023-09-01 08:14 UTC, shumpei07 commented on lesson3.php
> +echo $human['age']['gender'];
お疲れ様です。

「歳・」訂正しました。
ご確認お願いします。

2023-09-04 02:12 UTC, shumpei07 commented on lesson3.php
> +echo $human['age']['gender'];
変数の訂正完了しました。
宜しくお願いします。

2023-09-04 06:18 UTC, shumpei07 commented
次の単元からブランチ分けます。

2023-09-04 06:33 UTC, uchiyama4929 commented on 03.繰り返し処理/lesson5.php
> +    }
```
for ($j = 1; $j <= $rows - $i; $j++) {
        echo "*";
    }
```
このようにアスタリスクを出してもらう予定だったのですが
繰り返し処理はすべて使いこなせているようでしたので差し戻しはなしで行きます。

2023-09-04 06:34 UTC, uchiyama4929 approved these changes

2023-09-04 06:36 UTC, merged